version: "3"

networks:
  monitor-net:
    driver: bridge

services:
  surveyor:
    build: ../
    container_name: nats-surveyor
    restart: always
    volumes:
      - ./observations:/observations
      - ./jetstream:/jetstream
    entrypoint: /nats-surveyor
    command: -c ${NATS_SURVEYOR_SERVER_COUNT} -jwt "${NATS_SURVEYOR_JWT}" -s "${NATS_SURVEYOR_SERVERS}" -observe /observations #-jetstream /jetstream
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"

  prometheus:
    image: prom/prometheus:${PROMETHEUS_DOCKER_TAG}
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - $PROMETHEUS_STORAGE:/usr/local/share/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/usr/local/share/prometheus
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - surveyor

  grafana:
    image: grafana/grafana:${GRAFANA_DOCKER_TAG}
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - prometheus
